# Generated by Django 4.2.3 on 2023-07-05 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('theme', '0002_theme_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customuser'),
        ),
    ]
