# Generated by Django 4.2.3 on 2023-07-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_alter_theme_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='author',
        ),
    ]
